### ISSUE TITLE
Spec Teardown is called in wrong order

### ISSUE THREAD

**Issue by lukaszmn** [shikaan/titef#36]
I added a second `spec` to `spec-setup-teardown.specs.js`:

```js
...
        messages.push('suite:callback');
        spec('b', () => {
          messages.push('spec-b:callback');
        });
        spec('c', () => {
          messages.push('spec-c:callback');
        });
...
```

and the list of events was in this order:
```
suite:setup
suite:callback

spec:setup
spec-b:callback
spec:setup
spec-c:callback
spec:teardown
spec:teardown

suite:teardown
```

I rather expected the following order:
```
suite:setup
suite:callback

spec:setup
spec-b:callback
spec:teardown
spec:setup
spec-c:callback
spec:teardown

suite:teardown
```

**Comment by shikaan** [comment]
Hey @lukaszmn

What you expect there is the behaviour for synchronous tests. 

For `async` there's no assurance on the order of `teardown` and `setup` because the all the specs are executed "in parallel" (in JavaScript terms of course) which is the reason why Titef is so fast. 

The only thing we are able to guarantee is that _for a given spec_ the `setup` happens before the test callback and the `teardown` happens after, but we given the async nature of the framework there is no way to control whether another `teardown` for another `spec` has already been executed.

Does this answer the question?

**Comment by lukaszmn** [comment]
Hi, thanks for the explanation. Now when I think about it, does it make any sense to add `spec:setup` and `spec:teardown` in this async/parallel case? I think it introduces more confusion and maybe titef should warn me about that or even throw an error?

I haven't noticed that explanation in the documentation, I might have missed it, but if it's not present, definitely it's worth adding.

Thanks

**Comment by shikaan** [comment]
I think it's worth still having those hooks there.

> **Example**
> You have some code who modifies a row in a database and you want to test it. Steps would be:
> 1. Create that specific row
> 2. Modify the row and check the result
> 3. Delete that row from database

The steps above are expected to occur in this order using the hooks, but you need to be mindful of using different rows for different tests, otherwise different tests can step on each other's toe.

Regarding documentation, this behaviour is documented [here](https://shikaan.github.io/titef/api/spec/#remarks-and-caveats), but it's probably not as clear as it should be. Do you have any suggestion to improve this section?

**Comment by lukaszmn** [comment]
Maybe that doc:

https://shikaan.github.io/titef/api/spec/#remarks-and-caveats
If that's the case, `eachSetup` and `eachTeardown` are not guaranteed to be executed directly before and after every `spec`, e.g. it may happen that a test with 3 `spec`s will run 3 `eachSetup`s before them all, then a series of `spec`s, and finally all `eachTeardown`s in a row.


https://shikaan.github.io/titef/api/suite/
A note in the table next to `eachSetup` and `eachTeardown`: they are not guaranteed to be executed in the order when `spec`s are asynchronous. See the note in https://shikaan.github.io/titef/api/spec/#remarks-and-caveats

**Comment by shikaan** [comment]
I have added an explanation with an example (inspired by this issue) here:
https://titef.netlify.com/api/spec/#remarks-and-caveats 

I would not stress to much on the "not being in order" which is the reason I didn't add the table part. Callbacks are actually are in the right order, because for each `spec` the setup/spec/teardown sequence is achieved. 

Problems might rise only in case of non-independent tests, but given that tests should generally be independent as a rule, I would not clutter the definition table with a very specific case.

**Comment by shikaan** [comment]
Given the lack of inputs, I would call this done. If needed can reopen
